
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Hero",
  "author": "Someone",
  "url": "woohoo",
  "likes": 150
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "test",
  "name": "test",
  "password": "1234"
}

### 
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Andy515",
  "name": "Andy",
  "password": "Andy"
}

###
GET http://localhost:3003/api/users


### 
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Hero",
  "author": "Someone",
  "url": "woohoo",
  "likes": 150,
  "userId": "610b1e4fcb4bea1250b3c402"
}