POST https://damp-ridge-84274.herokuapp.com/api/persons
content-type: application/json

{
    "name": "Alex",
    "number": "123-456-789"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Arto Hellas", 
    "number": "040-123456"
}

###
DELETE http://localhost:3001/api/persons/60f09c9ae634dd06441ecdc3
content-type: application/json
